apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    app: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: vishwa275/javaimage:latest # Replace with specific tag if needed
        ports:
        - containerPort: 8080 # Ensure this matches your application's configuration
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod" # Example: Spring Boot profile
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
